baseURL: "https://example.org/"
languageCode: en-us
title: Three Cities 

module:
  mounts:
    - source: static
      target: static
    - source: assets
      target: assets
    - source: "node_modules/bootstrap"
      target: "assets/scss/bootstrap"
    - source: "node_modules/@fortawesome/fontawesome-free"
      target: "static/fontawesome"
    - source: "node_modules"
      target: "static/js"
    - source: "node_modules"
      target: "static/animatecss"